// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://musnpxaqapkvdjzmexrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11c25weGFxYXBrdmRqem1leHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTg0MjEsImV4cCI6MjA1OTUzNDQyMX0.4WT9OY_T_Fz1mNjcb8122qwpMgXgMI-vVTxNPmXxfe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);